# Base configs
baseurl: "https://kennethhwang.github.io/paintings"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Paintings by Kenny Hwang"
subtitle: "See the world through my eyes!"
author: "Kenny Hwang"
header:
 title: "Photography"
 subtitle: "by Kenny Hwang"
footer:
 name: "Hey there, my name is Kenny"
 bio: "I am a person from MD living in SF. Love playing games, learning painting and photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
